// GENERATED by sidecar/gen-shim.mjs — do not edit.
//
// Reproduces the Electron preload's contextBridge API on top of the saucer
// bridge, so the renderer bundle runs unmodified. Loaded as a classic script
// before the app module, because window.clui must exist before React mounts.
//
// Derived from src/preload/index.ts: 46 invoke, 12 send, 9 subscription methods.
(function () {
  // saucer's exposed functions are not installed yet when this classic script
  // runs, so buffer and flush. Losing the boot log to a swallowed exception is
  // exactly how a blank window becomes unexplainable.
  var logQueue = [];
  function ready() {
    return !!(window.saucer && window.saucer.exposed && window.saucer.exposed.shell_log);
  }
  function flushLog() {
    if (!ready()) return false;
    while (logQueue.length) {
      try { window.saucer.exposed.shell_log(String(logQueue.shift())); } catch (e) { return false; }
    }
    return true;
  }
  function shellLog(msg) {
    logQueue.push(msg);
    flushLog();
  }
  var flushTimer = setInterval(function () {
    if (flushLog() && logQueue.length === 0) { /* keep polling; more may arrive */ }
  }, 50);
  setTimeout(function () { clearInterval(flushTimer); }, 20000);

  // The GUI subsystem has no console, so surface failures where they can be read.
  window.addEventListener('error', function (e) {
    shellLog('uncaught: ' + (e.message || e.error) + ' @ ' + (e.filename || '?') + ':' + e.lineno);
  });
  window.addEventListener('unhandledrejection', function (e) {
    shellLog('unhandled rejection: ' + ((e.reason && (e.reason.stack || e.reason.message)) || e.reason));
  });

  var pending = new Map();
  var listeners = new Map();
  var nextId = 1;

  function bridgeSend(obj) {
    if (window.saucer && window.saucer.exposed && window.saucer.exposed.bridge_send) {
      window.saucer.exposed.bridge_send(JSON.stringify(obj));
      return true;
    }
    return false;
  }

  function invoke(channel, args) {
    var id = nextId++;
    return new Promise(function (resolve, reject) {
      pending.set(id, { resolve: resolve, reject: reject, channel: channel });
      if (!bridgeSend({ id: id, channel: channel, args: args })) {
        pending.delete(id);
        reject(new Error('bridge unavailable'));
      }
    });
  }

  function fire(channel, args) {
    bridgeSend({ channel: channel, args: args });
  }

  function on(channel, cb) {
    if (!listeners.has(channel)) listeners.set(channel, new Set());
    listeners.get(channel).add(cb);
    return function () { listeners.get(channel).delete(cb); };
  }

  // Called by C++ with each line the sidecar emits.
  window.__bridgeReceive = function (raw) {
    var msg;
    try { msg = typeof raw === 'string' ? JSON.parse(raw) : raw; } catch (e) { return; }
    if (!msg) return;

    if (msg.event) {
      var set = listeners.get(msg.event);
      if (set) set.forEach(function (fn) { try { fn(msg.payload); } catch (e) { console.error(e); } });
      return;
    }

    var p = pending.get(msg.id);
    if (!p) return;
    pending.delete(msg.id);
    if (msg.ok) p.resolve(msg.result);
    else p.reject(new Error(p.channel + ': ' + msg.error));
  };

  window.clui = {
    start: function () { return invoke("clui:start"); },
    createTab: function () { return invoke("clui:create-tab"); },
    prompt: function (tabId, requestId, options) { return invoke("clui:prompt", { tabId, requestId, options }); },
    cancel: function (requestId) { return invoke("clui:cancel", requestId); },
    stopTab: function (tabId) { return invoke("clui:stop-tab", tabId); },
    retry: function (tabId, requestId, options) { return invoke("clui:retry", { tabId, requestId, options }); },
    status: function () { return invoke("clui:status"); },
    tabHealth: function () { return invoke("clui:tab-health"); },
    closeTab: function (tabId) { return invoke("clui:close-tab", tabId); },
    selectDirectory: function () { return invoke("clui:select-directory"); },
    openExternal: function (url) { return invoke("clui:open-external", url); },
    openInTerminal: function (sessionId, projectPath) { return invoke("clui:open-in-terminal", { sessionId, projectPath }); },
    attachFiles: function () { return invoke("clui:attach-files"); },
    takeScreenshot: function () { return invoke("clui:take-screenshot"); },
    pasteImage: function (dataUrl) { return invoke("clui:paste-image", dataUrl); },
    transcribeAudio: function (audioBase64) { return invoke("clui:transcribe-audio", audioBase64); },
    exportConversation: function (args) { return invoke("clui:export-conversation", args); },
    getDiagnostics: function () { return invoke("clui:get-diagnostics"); },
    respondPermission: function (tabId, questionId, optionId) { return invoke("clui:respond-permission", { tabId, questionId, optionId }); },
    listSessions: function (projectPath?: string) { return invoke("clui:list-sessions", projectPath); },
    loadSession: function (sessionId: string, projectPath?: string) { return invoke("clui:load-session", { sessionId, projectPath }); },
    fetchMarketplace: function (forceRefresh) { return invoke("clui:marketplace-fetch", { forceRefresh }); },
    listInstalledPlugins: function () { return invoke("clui:marketplace-installed"); },
    installPlugin: function (repo, pluginName, marketplace, sourcePath, isSkillMd) { return invoke("clui:marketplace-install", { repo, pluginName, marketplace, sourcePath, isSkillMd }); },
    uninstallPlugin: function (pluginName) { return invoke("clui:marketplace-uninstall", { pluginName }); },
    openclawHealth: function () { return invoke("clui:openclaw-health"); },
    openclawOnboard: function () { return invoke("clui:openclaw-onboard"); },
    openPath: function (path) { return invoke("clui:open-path", path); },
    openclawModelInfo: function () { return invoke("clui:openclaw-model-info"); },
    openclawSetModel: function (provider, model) { return invoke("clui:openclaw-set-model", { provider, model }); },
    openclawRun: function (action) { return invoke("clui:openclaw-run", { action }); },
    getRuntimeMetrics: function () { return invoke("clui:get-runtime-metrics"); },
    nodeStatus: function () { return invoke("clui:node-status"); },
    nodeAction: function (action) { return invoke("clui:node-action", { action }); },
    gatewayStatus: function () { return invoke("clui:gateway-status"); },
    gatewayProbe: function () { return invoke("clui:gateway-probe"); },
    gatewayConfigGet: function () { return invoke("clui:gateway-config-get"); },
    gatewayConfigSet: function (patch) { return invoke("clui:gateway-config-set", patch); },
    getConnectionTarget: function () { return invoke("clui:get-connection-target"); },
    setConnectionTarget: function (target) { return invoke("clui:set-connection-target", target); },
    getShortcuts: function () { return invoke("clui:get-shortcuts"); },
    exportTheme: function (theme, suggestedName) { return invoke("clui:theme-export", { theme, suggestedName }); },
    importTheme: function () { return invoke("clui:theme-import"); },
    getTheme: function () { return invoke("clui:get-theme"); },
    animateHeight: function (from, to, durationMs) { return invoke("clui:animate-height", { from, to, durationMs }); },
    isVisible: function () { return invoke("clui:is-visible"); },

    initSession: function (tabId) { fire("clui:init-session", tabId); },
    resetTabSession: function (tabId) { fire("clui:reset-tab-session", tabId); },
    setBranding: function (branding) { fire("clui:set-branding", branding); },
    traceShell: function (line) { fire("clui:trace-shell", line); },
    setPermissionMode: function (mode) { fire("clui:set-permission-mode", mode); },
    resizeHeight: function (height) { fire("clui:resize-height", height); },
    hideWindow: function () { fire("clui:hide-window"); },
    setIgnoreMouseEvents: function (ignore, options) { fire("clui:set-ignore-mouse-events", ignore, options || {}); },
    setWindowWidth: function (width) { fire("clui:set-window-width", width); },
    windowReady: function (generation) { fire("clui:window-ready", generation); },
    dismissReady: function (generation) { fire("clui:window-dismiss-ready", generation); },
    setDragHolding: function (holding) { fire("clui:drag-holding", holding); },

    onThemeChange: function (callback) { return on("clui:theme-changed", function (p) {
      if (p && typeof p === 'object' && !Array.isArray(p)) {
        var keys = Object.keys(p);
        return callback.apply(null, keys.map(function (k) { return p[k]; }));
      }
      return callback(p);
    }); },
    onEvent: function (callback) { return on("clui:normalized-event", function (p) {
      if (p && typeof p === 'object' && !Array.isArray(p)) {
        var keys = Object.keys(p);
        return callback.apply(null, keys.map(function (k) { return p[k]; }));
      }
      return callback(p);
    }); },
    onTabStatusChange: function (callback) { return on("clui:tab-status-change", function (p) {
      if (p && typeof p === 'object' && !Array.isArray(p)) {
        var keys = Object.keys(p);
        return callback.apply(null, keys.map(function (k) { return p[k]; }));
      }
      return callback(p);
    }); },
    onError: function (callback) { return on("clui:enriched-error", function (p) {
      if (p && typeof p === 'object' && !Array.isArray(p)) {
        var keys = Object.keys(p);
        return callback.apply(null, keys.map(function (k) { return p[k]; }));
      }
      return callback(p);
    }); },
    onSkillStatus: function (callback) { return on("clui:skill-status", function (p) {
      if (p && typeof p === 'object' && !Array.isArray(p)) {
        var keys = Object.keys(p);
        return callback.apply(null, keys.map(function (k) { return p[k]; }));
      }
      return callback(p);
    }); },
    onWindowShown: function (callback) { return on("clui:window-shown", function (p) {
      if (p && typeof p === 'object' && !Array.isArray(p)) {
        var keys = Object.keys(p);
        return callback.apply(null, keys.map(function (k) { return p[k]; }));
      }
      return callback(p);
    }); },
    onWindowPrepare: function (callback) { return on("clui:window-prepare", function (p) {
      if (p && typeof p === 'object' && !Array.isArray(p)) {
        var keys = Object.keys(p);
        return callback.apply(null, keys.map(function (k) { return p[k]; }));
      }
      return callback(p);
    }); },
    onWindowDismiss: function (callback) { return on("clui:window-dismiss", function (p) {
      if (p && typeof p === 'object' && !Array.isArray(p)) {
        var keys = Object.keys(p);
        return callback.apply(null, keys.map(function (k) { return p[k]; }));
      }
      return callback(p);
    }); },
    onShortcutAction: function (callback) { return on("clui:shortcut-action", function (p) {
      if (p && typeof p === 'object' && !Array.isArray(p)) {
        var keys = Object.keys(p);
        return callback.apply(null, keys.map(function (k) { return p[k]; }));
      }
      return callback(p);
    }); },
  };

  // Diagnostics the shell reads back out.
  window.clui.__meta = { invokes: 46, sends: 12, events: 9 };
  shellLog('clui shim installed: ' + JSON.stringify(window.clui.__meta));
  window.addEventListener('DOMContentLoaded', function () {
    shellLog('DOMContentLoaded; root children=' + (document.getElementById('root') || {}).childElementCount);
    setTimeout(function () {
      var r = document.getElementById('root');
      shellLog('after 3s; root children=' + (r ? r.childElementCount : 'no root'));
    }, 3000);
  });
})();
