// Generate the page-side `window.clui` shim from src/preload/index.ts.
//
// The preload is the exact contract the renderer depends on: 46 invoke, 12 send
// and 9 subscription methods. Hand-copying that into a shim would rot the first
// time a channel is added, so it is derived instead — regenerate and the shim
// matches whatever the preload currently exposes.
//
// Usage: node sidecar/gen-shim.mjs <preload.ts> <types.ts> <out.js>

import { readFileSync, writeFileSync } from 'node:fs'

const [, , preloadPath, typesPath, outPath] = process.argv
if (!preloadPath || !typesPath || !outPath) {
  console.error('usage: gen-shim.mjs <preload.ts> <shared/types.ts> <out.js>')
  process.exit(1)
}

const preload = readFileSync(preloadPath, 'utf-8')
const types = readFileSync(typesPath, 'utf-8')

// IPC constant name -> wire string, so the shim can emit real channel names.
const channels = new Map()
for (const m of types.matchAll(/^\s+([A-Z0-9_]+):\s*'([^']+)'/gm)) {
  channels.set(m[1], m[2])
}

/**
 * The preload is TypeScript, so its parameter lists carry annotations —
 * `projectPath?: string` is not valid JavaScript and silently breaks the whole
 * shim with a SyntaxError, leaving window.clui undefined. Keep only the
 * identifiers.
 */
const stripTypes = (params) =>
  params
    .split(',')
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p) => p.replace(/[?:].*$/, '').replace(/^\.\.\./, '...').trim())
    .join(', ')

const resolve = (name) => {
  const wire = channels.get(name)
  if (!wire) throw new Error(`no IPC constant named ${name} in shared/types.ts`)
  return wire
}

const invokes = []
const sends = []
const events = []

// invoke: `name: (a, b) => ipcRenderer.invoke(IPC.X, <payload>)`
for (const m of preload.matchAll(
  /^\s{2}([a-zA-Z_][\w]*):\s*\(([^)]*)\)\s*=>\s*ipcRenderer\.invoke\(\s*(?:IPC\.([A-Z0-9_]+)|'([^']+)')\s*(?:,\s*([\s\S]*?))?\)\s*,?\s*$/gm,
)) {
  const [, name, params, constName, literal, payload] = m
  invokes.push({
    name,
    channel: constName ? resolve(constName) : literal,
    params: stripTypes(params),
    payload: (payload ?? '').trim(),
  })
}

// send: same shape, fire-and-forget
for (const m of preload.matchAll(
  /^\s{2}([a-zA-Z_][\w]*):\s*\(([^)]*)\)\s*=>\s*ipcRenderer\.send\(\s*(?:IPC\.([A-Z0-9_]+)|'([^']+)')\s*(?:,\s*([\s\S]*?))?\)\s*,?\s*$/gm,
)) {
  const [, name, params, constName, literal, payload] = m
  sends.push({
    name,
    channel: constName ? resolve(constName) : literal,
    params: stripTypes(params),
    payload: (payload ?? '').trim(),
  })
}

// subscriptions: `onX: (callback) => { ... ipcRenderer.on(IPC.Y, handler) ... }`
for (const m of preload.matchAll(
  /^\s{2}(on[A-Z][\w]*):\s*\([\s\S]*?ipcRenderer\.on\(\s*(?:IPC\.([A-Z0-9_]+)|'([^']+)')/gm,
)) {
  const [, name, constName, literal] = m
  events.push({ name, channel: constName ? resolve(constName) : literal })
}

const body = `// GENERATED by sidecar/gen-shim.mjs — do not edit.
//
// Reproduces the Electron preload's contextBridge API on top of the saucer
// bridge, so the renderer bundle runs unmodified. Loaded as a classic script
// before the app module, because window.clui must exist before React mounts.
//
// Derived from src/preload/index.ts: ${invokes.length} invoke, ${sends.length} send, ${events.length} subscription methods.
(function () {
  // saucer's exposed functions are not installed yet when this classic script
  // runs, so buffer and flush. Losing the boot log to a swallowed exception is
  // exactly how a blank window becomes unexplainable.
  var logQueue = [];
  function ready() {
    return !!(window.saucer && window.saucer.exposed && window.saucer.exposed.shell_log);
  }
  function flushLog() {
    if (!ready()) return false;
    while (logQueue.length) {
      try { window.saucer.exposed.shell_log(String(logQueue.shift())); } catch (e) { return false; }
    }
    return true;
  }
  function shellLog(msg) {
    logQueue.push(msg);
    flushLog();
  }
  var flushTimer = setInterval(function () {
    if (flushLog() && logQueue.length === 0) { /* keep polling; more may arrive */ }
  }, 50);
  setTimeout(function () { clearInterval(flushTimer); }, 20000);

  // The GUI subsystem has no console, so surface failures where they can be read.
  window.addEventListener('error', function (e) {
    shellLog('uncaught: ' + (e.message || e.error) + ' @ ' + (e.filename || '?') + ':' + e.lineno);
  });
  window.addEventListener('unhandledrejection', function (e) {
    shellLog('unhandled rejection: ' + ((e.reason && (e.reason.stack || e.reason.message)) || e.reason));
  });

  var pending = new Map();
  var listeners = new Map();
  var nextId = 1;

  function bridgeSend(obj) {
    if (window.saucer && window.saucer.exposed && window.saucer.exposed.bridge_send) {
      window.saucer.exposed.bridge_send(JSON.stringify(obj));
      return true;
    }
    return false;
  }

  function invoke(channel, args) {
    var id = nextId++;
    return new Promise(function (resolve, reject) {
      pending.set(id, { resolve: resolve, reject: reject, channel: channel });
      if (!bridgeSend({ id: id, channel: channel, args: args })) {
        pending.delete(id);
        reject(new Error('bridge unavailable'));
      }
    });
  }

  function fire(channel, args) {
    bridgeSend({ channel: channel, args: args });
  }

  function on(channel, cb) {
    if (!listeners.has(channel)) listeners.set(channel, new Set());
    listeners.get(channel).add(cb);
    return function () { listeners.get(channel).delete(cb); };
  }

  // Called by C++ with each line the sidecar emits.
  window.__bridgeReceive = function (raw) {
    var msg;
    try { msg = typeof raw === 'string' ? JSON.parse(raw) : raw; } catch (e) { return; }
    if (!msg) return;

    if (msg.event) {
      var set = listeners.get(msg.event);
      if (set) set.forEach(function (fn) { try { fn(msg.payload); } catch (e) { console.error(e); } });
      return;
    }

    var p = pending.get(msg.id);
    if (!p) return;
    pending.delete(msg.id);
    if (msg.ok) p.resolve(msg.result);
    else p.reject(new Error(p.channel + ': ' + msg.error));
  };

  window.clui = {
${invokes.map((i) => `    ${i.name}: function (${i.params}) { return invoke(${JSON.stringify(i.channel)}${i.payload ? ', ' + i.payload : ''}); },`).join('\n')}

${sends.map((s) => `    ${s.name}: function (${s.params}) { fire(${JSON.stringify(s.channel)}${s.payload ? ', ' + s.payload : ''}); },`).join('\n')}

${events
  .map((e) => {
    // The preload delivers positional callback args; the bridge carries one
    // payload object, so spread the known shapes back out.
    return `    ${e.name}: function (callback) { return on(${JSON.stringify(e.channel)}, function (p) {
      if (p && typeof p === 'object' && !Array.isArray(p)) {
        var keys = Object.keys(p);
        return callback.apply(null, keys.map(function (k) { return p[k]; }));
      }
      return callback(p);
    }); },`
  })
  .join('\n')}
  };

  // ─── Click-through hit regions ───
  //
  // saucer has no equivalent of Electron's setIgnoreMouseEvents(forward:true),
  // so the shell polls the cursor and toggles click-through against rectangles
  // the page publishes. The renderer already marks every interactive element
  // with data-clui-ui — the same attribute its Electron mousemove handler
  // hit-tested — so the rects come straight from existing markup and the
  // renderer needs no changes.
  //
  // Without this the rect list stays empty, every point reads as "not over",
  // and click-through is stuck on: the window is visible but inert.
  function publishHitRects() {
    if (!(window.saucer && window.saucer.exposed && window.saucer.exposed.set_hit_rects)) return;
    var flat = [];
    var els = document.querySelectorAll('[data-clui-ui]');
    for (var i = 0; i < els.length; i++) {
      var r = els[i].getBoundingClientRect();
      if (r.width < 1 || r.height < 1) continue;
      flat.push(Math.round(r.x), Math.round(r.y), Math.round(r.width), Math.round(r.height));
    }
    window.saucer.exposed.set_hit_rects(flat);
  }

  // Coalesce to one publish per frame: the UI animates, and a MutationObserver
  // on a React tree fires constantly.
  var rectsQueued = false;
  function scheduleHitRects() {
    if (rectsQueued) return;
    rectsQueued = true;
    requestAnimationFrame(function () { rectsQueued = false; publishHitRects(); });
  }

  window.addEventListener('DOMContentLoaded', function () {
    scheduleHitRects();
    new MutationObserver(scheduleHitRects).observe(document.documentElement, {
      subtree: true, childList: true, attributes: true,
      attributeFilter: ['style', 'class', 'data-clui-ui'],
    });
    window.addEventListener('resize', scheduleHitRects);
    // Animations move things without mutating the DOM, so sample for a while.
    setInterval(scheduleHitRects, 250);
  });

  // The renderer drives click-through itself under Electron. That is a window
  // concern, not a backend one, so intercept it here rather than forwarding it
  // to the sidecar where it would be silently dropped.
  window.clui.setIgnoreMouseEvents = function () { /* shell owns this now */ };

  // Window-lifecycle acks belong to the shell, not the sidecar. Left on the
  // default path they would be forwarded to Node and dropped, and the summon
  // handshake would fall back to its timeout every time.
  window.clui.windowReady = function (generation) {
    if (window.saucer && window.saucer.exposed && window.saucer.exposed.window_ready) {
      window.saucer.exposed.window_ready(generation | 0);
    }
  };
  window.clui.dismissReady = function (generation) {
    if (window.saucer && window.saucer.exposed && window.saucer.exposed.dismiss_ready) {
      window.saucer.exposed.dismiss_ready(generation | 0);
    }
  };

  // ─── Native UI ───
  //
  // Dialogs and screen capture need an owner HWND and the desktop DC, so C++
  // owns them. It returns paths; the sidecar turns those into the objects the
  // renderer expects. Overridden here rather than generated, because these are
  // the only methods whose implementation is split across both processes.
  var ex = function () { return (window.saucer && window.saucer.exposed) || {}; };

  window.clui.selectDirectory = function () {
    return Promise.resolve(ex().pick_folder ? ex().pick_folder() : '').then(function (p) {
      return p || null;
    });
  };

  window.clui.attachFiles = function () {
    return Promise.resolve(ex().pick_files ? ex().pick_files() : []).then(function (paths) {
      if (!paths || !paths.length) return [];
      return invoke('clui:describe-files', { paths: paths });
    });
  };

  window.clui.takeScreenshot = function () {
    return Promise.resolve(ex().capture_screen ? ex().capture_screen() : '').then(function (path) {
      if (!path) return null;
      return invoke('clui:describe-files', { paths: [path] }).then(function (list) {
        return (list && list[0]) || null;
      });
    });
  };

  window.clui.exportTheme = function (theme, suggestedName) {
    return Promise.resolve(ex().save_theme_file ? ex().save_theme_file(String(suggestedName || 'theme.json')) : '')
      .then(function (path) {
        if (!path) return { ok: false, cancelled: true };
        return invoke('clui:write-text-file', { path: path, content: JSON.stringify(theme, null, 2) });
      });
  };

  window.clui.importTheme = function () {
    return Promise.resolve(ex().open_theme_file ? ex().open_theme_file() : '').then(function (path) {
      if (!path) return { ok: false, cancelled: true };
      return invoke('clui:read-text-file', { path: path }).then(function (r) {
        if (!r.ok) return r;
        try {
          return { ok: true, theme: JSON.parse(r.content) };
        } catch (e) {
          return { ok: false, error: 'not valid JSON: ' + e.message };
        }
      });
    });
  };

  // Diagnostics the shell reads back out.
  window.clui.__meta = { invokes: ${invokes.length}, sends: ${sends.length}, events: ${events.length} };
  shellLog('clui shim installed: ' + JSON.stringify(window.clui.__meta));
  window.addEventListener('DOMContentLoaded', function () {
    shellLog('DOMContentLoaded; root children=' + (document.getElementById('root') || {}).childElementCount);
    setTimeout(function () {
      var r = document.getElementById('root');
      shellLog('after 3s; root children=' + (r ? r.childElementCount : 'no root'));
    }, 3000);
  });
})();
`

writeFileSync(outPath, body)
console.error(
  `[gen-shim] ${invokes.length} invoke, ${sends.length} send, ${events.length} events -> ${outPath}`,
)
