// GENERATED by sidecar/gen-shim.mjs — do not edit.
//
// Reproduces the Electron preload's contextBridge API on top of the saucer
// bridge, so the renderer bundle runs unmodified. Loaded as a classic script
// before the app module, because window.clui must exist before React mounts.
//
// Derived from src/preload/index.ts: 46 invoke, 12 send, 9 subscription methods.
(function () {
  // saucer's exposed functions are not installed yet when this classic script
  // runs, so buffer and flush. Losing the boot log to a swallowed exception is
  // exactly how a blank window becomes unexplainable.
  var logQueue = [];
  function ready() {
    return !!(window.saucer && window.saucer.exposed && window.saucer.exposed.shell_log);
  }
  function flushLog() {
    if (!ready()) return false;
    while (logQueue.length) {
      try { window.saucer.exposed.shell_log(String(logQueue.shift())); } catch (e) { return false; }
    }
    return true;
  }
  function shellLog(msg) {
    logQueue.push(msg);
    flushLog();
  }
  var flushTimer = setInterval(function () {
    if (flushLog() && logQueue.length === 0) { /* keep polling; more may arrive */ }
  }, 50);
  setTimeout(function () { clearInterval(flushTimer); }, 20000);

  // The GUI subsystem has no console, so surface failures where they can be read.
  window.addEventListener('error', function (e) {
    shellLog('uncaught: ' + (e.message || e.error) + ' @ ' + (e.filename || '?') + ':' + e.lineno);
  });
  window.addEventListener('unhandledrejection', function (e) {
    shellLog('unhandled rejection: ' + ((e.reason && (e.reason.stack || e.reason.message)) || e.reason));
  });

  var pending = new Map();
  var listeners = new Map();
  var nextId = 1;

  function bridgeSend(obj) {
    if (window.saucer && window.saucer.exposed && window.saucer.exposed.bridge_send) {
      window.saucer.exposed.bridge_send(JSON.stringify(obj));
      return true;
    }
    return false;
  }

  function invoke(channel, args) {
    var id = nextId++;
    return new Promise(function (resolve, reject) {
      pending.set(id, { resolve: resolve, reject: reject, channel: channel });
      if (!bridgeSend({ id: id, channel: channel, args: args })) {
        pending.delete(id);
        reject(new Error('bridge unavailable'));
      }
    });
  }

  function fire(channel, args) {
    bridgeSend({ channel: channel, args: args });
  }

  function on(channel, cb) {
    if (!listeners.has(channel)) listeners.set(channel, new Set());
    listeners.get(channel).add(cb);
    return function () { listeners.get(channel).delete(cb); };
  }

  // Called by C++ with each line the sidecar emits.
  window.__bridgeReceive = function (raw) {
    var msg;
    try { msg = typeof raw === 'string' ? JSON.parse(raw) : raw; } catch (e) { return; }
    if (!msg) return;

    if (msg.event) {
      // Positional args come over the wire. They are never inferred from an
      // object's shape, which shredded single-object handlers such as
      // onSkillStatus(status) into one argument per key.
      var args = Array.isArray(msg.args) ? msg.args : (msg.payload === undefined ? [] : [msg.payload]);
      var set = listeners.get(msg.event);
      if (set) set.forEach(function (fn) { try { fn.apply(null, args); } catch (e) { console.error(e); } });
      return;
    }

    var p = pending.get(msg.id);
    if (!p) return;
    pending.delete(msg.id);
    if (msg.ok) p.resolve(msg.result);
    else p.reject(new Error(p.channel + ': ' + msg.error));
  };

  window.clui = {
    start: function () { return invoke("clui:start"); },
    createTab: function () { return invoke("clui:create-tab"); },
    prompt: function (tabId, requestId, options) { return invoke("clui:prompt", { tabId, requestId, options }); },
    cancel: function (requestId) { return invoke("clui:cancel", requestId); },
    stopTab: function (tabId) { return invoke("clui:stop-tab", tabId); },
    retry: function (tabId, requestId, options) { return invoke("clui:retry", { tabId, requestId, options }); },
    status: function () { return invoke("clui:status"); },
    tabHealth: function () { return invoke("clui:tab-health"); },
    closeTab: function (tabId) { return invoke("clui:close-tab", tabId); },
    selectDirectory: function () { return invoke("clui:select-directory"); },
    openExternal: function (url) { return invoke("clui:open-external", url); },
    openInTerminal: function (sessionId, projectPath) { return invoke("clui:open-in-terminal", { sessionId, projectPath }); },
    attachFiles: function () { return invoke("clui:attach-files"); },
    takeScreenshot: function () { return invoke("clui:take-screenshot"); },
    pasteImage: function (dataUrl) { return invoke("clui:paste-image", dataUrl); },
    transcribeAudio: function (audioBase64) { return invoke("clui:transcribe-audio", audioBase64); },
    exportConversation: function (args) { return invoke("clui:export-conversation", args); },
    getDiagnostics: function () { return invoke("clui:get-diagnostics"); },
    respondPermission: function (tabId, questionId, optionId) { return invoke("clui:respond-permission", { tabId, questionId, optionId }); },
    listSessions: function (projectPath) { return invoke("clui:list-sessions", projectPath); },
    loadSession: function (sessionId, projectPath) { return invoke("clui:load-session", { sessionId, projectPath }); },
    fetchMarketplace: function (forceRefresh) { return invoke("clui:marketplace-fetch", { forceRefresh }); },
    listInstalledPlugins: function () { return invoke("clui:marketplace-installed"); },
    installPlugin: function (repo, pluginName, marketplace, sourcePath, isSkillMd) { return invoke("clui:marketplace-install", { repo, pluginName, marketplace, sourcePath, isSkillMd }); },
    uninstallPlugin: function (pluginName) { return invoke("clui:marketplace-uninstall", { pluginName }); },
    openclawHealth: function () { return invoke("clui:openclaw-health"); },
    openclawOnboard: function () { return invoke("clui:openclaw-onboard"); },
    openPath: function (path) { return invoke("clui:open-path", path); },
    openclawModelInfo: function () { return invoke("clui:openclaw-model-info"); },
    openclawSetModel: function (provider, model) { return invoke("clui:openclaw-set-model", { provider, model }); },
    openclawRun: function (action) { return invoke("clui:openclaw-run", { action }); },
    getRuntimeMetrics: function () { return invoke("clui:get-runtime-metrics"); },
    nodeStatus: function () { return invoke("clui:node-status"); },
    nodeAction: function (action) { return invoke("clui:node-action", { action }); },
    gatewayStatus: function () { return invoke("clui:gateway-status"); },
    gatewayProbe: function () { return invoke("clui:gateway-probe"); },
    gatewayConfigGet: function () { return invoke("clui:gateway-config-get"); },
    gatewayConfigSet: function (patch) { return invoke("clui:gateway-config-set", patch); },
    getConnectionTarget: function () { return invoke("clui:get-connection-target"); },
    setConnectionTarget: function (target) { return invoke("clui:set-connection-target", target); },
    getShortcuts: function () { return invoke("clui:get-shortcuts"); },
    exportTheme: function (theme, suggestedName) { return invoke("clui:theme-export", { theme, suggestedName }); },
    importTheme: function () { return invoke("clui:theme-import"); },
    getTheme: function () { return invoke("clui:get-theme"); },
    animateHeight: function (from, to, durationMs) { return invoke("clui:animate-height", { from, to, durationMs }); },
    isVisible: function () { return invoke("clui:is-visible"); },

    initSession: function (tabId) { fire("clui:init-session", tabId); },
    resetTabSession: function (tabId) { fire("clui:reset-tab-session", tabId); },
    setBranding: function (branding) { fire("clui:set-branding", branding); },
    traceShell: function (line) { fire("clui:trace-shell", line); },
    setPermissionMode: function (mode) { fire("clui:set-permission-mode", mode); },
    resizeHeight: function (height) { fire("clui:resize-height", height); },
    hideWindow: function () { fire("clui:hide-window"); },
    setIgnoreMouseEvents: function (ignore, options) { fire("clui:set-ignore-mouse-events", ignore, options || {}); },
    setWindowWidth: function (width) { fire("clui:set-window-width", width); },
    windowReady: function (generation) { fire("clui:window-ready", generation); },
    dismissReady: function (generation) { fire("clui:window-dismiss-ready", generation); },
    setDragHolding: function (holding) { fire("clui:drag-holding", holding); },

    onThemeChange: function (callback) { return on("clui:theme-changed", callback); },
    onEvent: function (callback) { return on("clui:normalized-event", callback); },
    onTabStatusChange: function (callback) { return on("clui:tab-status-change", callback); },
    onError: function (callback) { return on("clui:enriched-error", callback); },
    onSkillStatus: function (callback) { return on("clui:skill-status", callback); },
    onWindowShown: function (callback) { return on("clui:window-shown", callback); },
    onWindowPrepare: function (callback) { return on("clui:window-prepare", callback); },
    onWindowDismiss: function (callback) { return on("clui:window-dismiss", callback); },
    onShortcutAction: function (callback) { return on("clui:shortcut-action", callback); },
  };

  // ─── Click-through hit regions ───
  //
  // saucer has no equivalent of Electron's setIgnoreMouseEvents(forward:true),
  // so the shell polls the cursor and toggles click-through against rectangles
  // the page publishes. The renderer already marks every interactive element
  // with data-clui-ui — the same attribute its Electron mousemove handler
  // hit-tested — so the rects come straight from existing markup and the
  // renderer needs no changes.
  //
  // Without this the rect list stays empty, every point reads as "not over",
  // and click-through is stuck on: the window is visible but inert.
  function publishHitRects() {
    if (!(window.saucer && window.saucer.exposed && window.saucer.exposed.set_hit_rects)) return;
    var flat = [];
    var els = document.querySelectorAll('[data-clui-ui]');
    for (var i = 0; i < els.length; i++) {
      var r = els[i].getBoundingClientRect();
      if (r.width < 1 || r.height < 1) continue;
      flat.push(Math.round(r.x), Math.round(r.y), Math.round(r.width), Math.round(r.height));
    }
    window.saucer.exposed.set_hit_rects(flat);
  }

  // Coalesce to one publish per frame: the UI animates, and a MutationObserver
  // on a React tree fires constantly.
  var rectsQueued = false;
  function scheduleHitRects() {
    if (rectsQueued) return;
    rectsQueued = true;
    requestAnimationFrame(function () { rectsQueued = false; publishHitRects(); });
  }

  window.addEventListener('DOMContentLoaded', function () {
    scheduleHitRects();
    new MutationObserver(scheduleHitRects).observe(document.documentElement, {
      subtree: true, childList: true, attributes: true,
      attributeFilter: ['style', 'class', 'data-clui-ui'],
    });
    window.addEventListener('resize', scheduleHitRects);
    // Animations move things without mutating the DOM, so sample for a while.
    setInterval(scheduleHitRects, 250);
  });

  // The renderer drives click-through itself under Electron. That is a window
  // concern, not a backend one, so intercept it here rather than forwarding it
  // to the sidecar where it would be silently dropped.
  window.clui.setIgnoreMouseEvents = function () { /* shell owns this now */ };

  // Window-lifecycle acks belong to the shell, not the sidecar. Left on the
  // default path they would be forwarded to Node and dropped, and the summon
  // handshake would fall back to its timeout every time.
  window.clui.windowReady = function (generation) {
    if (window.saucer && window.saucer.exposed && window.saucer.exposed.window_ready) {
      window.saucer.exposed.window_ready(generation | 0);
    }
  };
  window.clui.dismissReady = function (generation) {
    if (window.saucer && window.saucer.exposed && window.saucer.exposed.dismiss_ready) {
      window.saucer.exposed.dismiss_ready(generation | 0);
    }
  };

  // ─── Native UI ───
  //
  // Dialogs and screen capture need an owner HWND and the desktop DC, so C++
  // owns them. It returns paths; the sidecar turns those into the objects the
  // renderer expects. Overridden here rather than generated, because these are
  // the only methods whose implementation is split across both processes.
  var ex = function () { return (window.saucer && window.saucer.exposed) || {}; };

  window.clui.selectDirectory = function () {
    return Promise.resolve(ex().pick_folder ? ex().pick_folder() : '').then(function (p) {
      return p || null;
    });
  };

  window.clui.attachFiles = function () {
    return Promise.resolve(ex().pick_files ? ex().pick_files() : []).then(function (paths) {
      if (!paths || !paths.length) return [];
      return invoke('clui:describe-files', { paths: paths });
    });
  };

  window.clui.takeScreenshot = function () {
    return Promise.resolve(ex().capture_screen ? ex().capture_screen() : '').then(function (path) {
      if (!path) return null;
      return invoke('clui:describe-files', { paths: [path] }).then(function (list) {
        return (list && list[0]) || null;
      });
    });
  };

  window.clui.exportTheme = function (theme, suggestedName) {
    return Promise.resolve(ex().save_theme_file ? ex().save_theme_file(String(suggestedName || 'theme.json')) : '')
      .then(function (path) {
        if (!path) return { ok: false, cancelled: true };
        return invoke('clui:write-text-file', { path: path, content: JSON.stringify(theme, null, 2) });
      });
  };

  window.clui.importTheme = function () {
    return Promise.resolve(ex().open_theme_file ? ex().open_theme_file() : '').then(function (path) {
      if (!path) return { ok: false, cancelled: true };
      return invoke('clui:read-text-file', { path: path }).then(function (r) {
        if (!r.ok) return r;
        try {
          return { ok: true, theme: JSON.parse(r.content) };
        } catch (e) {
          return { ok: false, error: 'not valid JSON: ' + e.message };
        }
      });
    });
  };

  // Diagnostics the shell reads back out.
  window.clui.__meta = { invokes: 46, sends: 12, events: 9 };
  shellLog('clui shim installed: ' + JSON.stringify(window.clui.__meta));
  window.addEventListener('DOMContentLoaded', function () {
    shellLog('DOMContentLoaded; root children=' + (document.getElementById('root') || {}).childElementCount);
    setTimeout(function () {
      var r = document.getElementById('root');
      shellLog('after 3s; root children=' + (r ? r.childElementCount : 'no root'));
    }, 3000);
  });
})();
