import { describe, expect, it } from 'vitest'
import {
  SOURCES,
  bareArgMap,
  declaredApiMethods,
  forwardsPrimitive,
  implementedApiMethods,
  ipcChannels,
  isBarePayload,
  payloadKeys,
  shimMethods,
  shimOverrides,
  sidecarHandlers,
  splitTopLevel,
} from '../helpers/contract'

/**
 * The bridge has four independent representations of the same API:
 *
 *   src/shared/clui-contract.ts   the declaration the renderer types against
 *   shell/web/clui-shim.js        the generated code the renderer actually calls
 *   sidecar/index.ts              the handlers that answer
 *   src/shared/types.ts           the wire strings all three agree on
 *
 * Nothing in the type system connects them: the contract is never executed, the
 * shim is generated JavaScript, and the sidecar keys its handler map by the
 * same constants but with no compile-time link to the caller's argument shape.
 * Drift between any two is a silent runtime failure — a button that does
 * nothing. These tests are the only thing holding them together.
 */

/**
 * Methods the shim reassigns to call saucer directly. Read out of the shim, so
 * moving a method between the shell and the sidecar needs no test edit — but
 * also cannot quietly exempt itself from the checks below.
 */
const overridden = shimOverrides()

describe('IPC channel table', () => {
  const channels = ipcChannels()

  it('parses a non-trivial channel table', () => {
    expect(channels.size).toBeGreaterThan(40)
  })

  it('maps every constant to a unique wire string', () => {
    const seen = new Map<string, string>()
    const collisions: string[] = []
    for (const [name, wire] of channels) {
      const prior = seen.get(wire)
      if (prior) collisions.push(`${prior} and ${name} both use "${wire}"`)
      else seen.set(wire, name)
    }
    expect(collisions).toEqual([])
  })

  it('namespaces every wire string under clui:', () => {
    const stray = [...channels].filter(([, wire]) => !wire.startsWith('clui:'))
    expect(stray).toEqual([])
  })
})

describe('contract declaration vs implementation', () => {
  const declared = declaredApiMethods()
  const implemented = implementedApiMethods()
  const implementedNames = new Set(implemented.map((m) => m.name))

  it('implements every method the CluiAPI interface declares', () => {
    const missing = declared.filter((n) => !implementedNames.has(n))
    expect(missing).toEqual([])
  })

  it('declares every method it implements', () => {
    const declaredSet = new Set(declared)
    const undeclared = implemented.map((m) => m.name).filter((n) => !declaredSet.has(n))
    expect(undeclared).toEqual([])
  })

  it('never reuses one method name for two transports', () => {
    const byName = new Map<string, string[]>()
    for (const m of implemented) {
      byName.set(m.name, [...(byName.get(m.name) ?? []), m.transport])
    }
    const dupes = [...byName].filter(([, t]) => t.length > 1)
    expect(dupes).toEqual([])
  })
})

describe('generated shim', () => {
  const implemented = implementedApiMethods()
  const shim = new Set(shimMethods())

  it('is regenerated from the current contract', () => {
    // A stale shim is the single most likely bridge failure: the contract gains
    // a method, nobody runs `npm run shim`, and the renderer calls undefined.
    const missing = implemented.map((m) => m.name).filter((n) => !shim.has(n))
    expect(missing).toEqual([])
  })

  it('carries the generated-file banner', () => {
    expect(SOURCES.shim()).toMatch(/GENERATED by sidecar\/gen-shim\.mjs/)
  })

  it('agrees with the contract on how many methods there are', () => {
    const meta = /__meta = \{ invokes: (\d+), sends: (\d+), events: (\d+) \}/.exec(SOURCES.shim())
    expect(meta, 'shim is missing its __meta counter').not.toBeNull()

    const counts = { invoke: 0, send: 0, subscribe: 0 }
    for (const m of implemented) counts[m.transport]++

    expect({
      invokes: Number(meta![1]),
      sends: Number(meta![2]),
      events: Number(meta![3]),
    }).toEqual({ invokes: counts.invoke, sends: counts.send, events: counts.subscribe })
  })
})

describe('sidecar handlers', () => {
  const implemented = implementedApiMethods()
  const handlers = sidecarHandlers()
  const handled = new Set(handlers.map((h) => h.constName))

  it('answers every request-response channel the renderer can call', () => {
    const unanswered = implemented
      .filter((m) => m.transport === 'invoke')
      .filter((m) => m.constName && !overridden.has(m.name) && !handled.has(m.constName))
      .map((m) => `${m.name} -> ${m.channel}`)
    expect(unanswered).toEqual([])
  })

  it('answers every fire-and-forget channel the renderer can call', () => {
    const unanswered = implemented
      .filter((m) => m.transport === 'send')
      .filter((m) => m.constName && !overridden.has(m.name) && !handled.has(m.constName))
      .map((m) => `${m.name} -> ${m.channel}`)
    expect(unanswered).toEqual([])
  })

  it('keeps every shell override on a method the contract declares', () => {
    // An override for a method nobody declares is dead code in the shim; an
    // override that outlives its contract entry silently shadows nothing.
    const declared = new Set(declaredApiMethods())
    const stray = [...overridden].filter((n) => !declared.has(n))
    expect(stray).toEqual([])
  })

  it('has no handler for a channel nothing can reach', () => {
    const reachable = new Set(
      implemented.filter((m) => m.constName).map((m) => m.constName as string),
    )
    // The shim hand-writes a few composite methods on top of lower-level
    // channels, so those are reachable without appearing in the contract.
    const shimText = SOURCES.shim()
    const channels = ipcChannels()
    const orphans = handlers
      .filter((h) => !reachable.has(h.constName))
      .filter((h) => !shimText.includes(`'${channels.get(h.constName)}'`))
      .map((h) => h.constName)
    expect(orphans).toEqual([])
  })
})

describe('bare-argument adaptation', () => {
  /**
   * The regression this exists for: the contract forwards a primitive
   * (`invoke(IPC.CANCEL, requestId)`) but the handler destructures an object
   * (`({ requestId }) => ...`). Destructuring a string yields `undefined`, so
   * cancel silently stops cancelling. `normalizeArgs` bridges the two via
   * `BARE_ARG` — but only for channels somebody remembered to list.
   */
  const implemented = implementedApiMethods()
  const handlers = new Map(sidecarHandlers().map((h) => [h.constName, h]))
  const bare = bareArgMap()

  const needsAdapter = implemented.filter(
    (m) =>
      m.transport !== 'subscribe' &&
      m.constName !== null &&
      !overridden.has(m.name) &&
      isBarePayload(m.payload) &&
      // An identifier holding an object survives `normalizeArgs` untouched;
      // only a primitive is at risk of being destructured into undefined.
      forwardsPrimitive(m.name) &&
      (handlers.get(m.constName)?.destructured.length ?? 0) > 0,
  )

  it('finds the channels that genuinely forward a primitive', () => {
    // Guards the guard: if the parser stops recognising bare payloads this set
    // silently empties and every assertion below passes vacuously.
    expect(needsAdapter.length).toBeGreaterThan(4)
  })

  it('registers every bare payload whose handler destructures', () => {
    const unmapped = needsAdapter
      .filter((m) => !bare.has(m.constName as string))
      .map((m) => `${m.name}: sends bare "${m.payload}" but the handler destructures`)
    expect(unmapped).toEqual([])
  })

  it('wraps each bare payload under the key its handler destructures', () => {
    const mismatched: string[] = []
    for (const m of needsAdapter) {
      const key = bare.get(m.constName as string)
      const handler = handlers.get(m.constName as string)!
      if (key && !handler.destructured.includes(key)) {
        mismatched.push(
          `${m.name}: BARE_ARG wraps as "${key}" but the handler destructures ` +
            `{ ${handler.destructured.join(', ')} }`,
        )
      }
    }
    expect(mismatched).toEqual([])
  })

  it('has no BARE_ARG entry for a channel that already sends an object', () => {
    const byConst = new Map(implemented.filter((m) => m.constName).map((m) => [m.constName, m]))
    const pointless: string[] = []
    for (const [constName] of bare) {
      const m = byConst.get(constName)
      if (m && m.payload && !isBarePayload(m.payload)) {
        pointless.push(`${constName}: contract already sends an object (${m.payload})`)
      }
    }
    expect(pointless).toEqual([])
  })
})

describe('object payload keys reach the handler', () => {
  /**
   * The counterpart to the bare-argument check, and the one that catches the
   * more common mistake: the contract sends `{ action }`, the handler
   * destructures `{ args }`, and every call arrives with `undefined`. Nothing
   * else in the toolchain connects these two — the handler map is keyed by
   * channel constant and typed `(args: any)`.
   */
  const implemented = implementedApiMethods()
  const handlers = new Map(sidecarHandlers().map((h) => [h.constName, h]))

  const withObjectPayloads = implemented
    .filter((m) => m.transport !== 'subscribe' && m.constName && !overridden.has(m.name))
    .map((m) => ({ method: m, keys: payloadKeys(m.payload), handler: handlers.get(m.constName!) }))
    .filter((e): e is { method: typeof implemented[number]; keys: string[]; handler: NonNullable<ReturnType<typeof handlers.get>> } =>
      e.keys !== null && e.keys.length > 0 && e.handler !== undefined)

  it('finds the object-payload channels', () => {
    expect(withObjectPayloads.length).toBeGreaterThan(5)
  })

  it('destructures only keys the contract actually sends', () => {
    const mismatched: string[] = []
    for (const { method, keys, handler } of withObjectPayloads) {
      const missing = handler.destructured.filter((k) => !keys.includes(k))
      if (missing.length > 0) {
        mismatched.push(
          `${method.name} (${method.channel}): handler destructures { ${missing.join(', ')} } ` +
            `but the contract sends { ${keys.join(', ')} } — those arrive undefined`,
        )
      }
    }
    expect(mismatched).toEqual([])
  })
})

describe('handlers that take no payload', () => {
  /**
   * A method declared with no parameters sends nothing, so `normalizeArgs`
   * hands the handler `{}`. A handler that destructures anyway reads
   * `undefined` on every call — which is how `tabHealth` came to answer for a
   * tab id it was never given.
   */
  const implemented = implementedApiMethods()
  const handlers = new Map(sidecarHandlers().map((h) => [h.constName, h]))

  it('never destructures a payload the contract does not send', () => {
    const offenders: string[] = []
    for (const m of implemented) {
      if (m.transport === 'subscribe' || !m.constName || overridden.has(m.name)) continue
      if (m.payload !== '') continue
      const handler = handlers.get(m.constName)
      if (handler && handler.destructured.length > 0) {
        offenders.push(
          `${m.name} (${m.channel}): declared as ${m.name}() with no payload, ` +
            `but the handler destructures { ${handler.destructured.join(', ')} }`,
        )
      }
    }
    expect(offenders).toEqual([])
  })
})

describe('multi-argument sends', () => {
  /**
   * `fire(channel, args)` in the generated shim takes exactly one payload. A
   * contract entry that passes two — `send(IPC.X, a, b)` — generates
   * `fire("clui:x", a, b)`, and `b` is dropped on the floor with no error.
   */
  it('never forwards more than one payload expression', () => {
    const offenders = implementedApiMethods()
      .filter((m) => m.transport === 'send' && !overridden.has(m.name))
      .filter((m) => splitTopLevel(m.payload).length > 1)
      .map((m) => `${m.name}: send(..., ${m.payload}) — the shim's fire() drops all but the first`)
    expect(offenders).toEqual([])
  })
})
