#!/usr/bin/env node
/**
 * Build an Android APK.
 *
 * Wraps Gradle rather than being called directly for two reasons, both of
 * which otherwise fail in ways that do not name their cause:
 *
 *  1. **`EXPO_NO_METRO_WORKSPACE_ROOT`.** In an npm workspace, Expo's CLI puts
 *     Metro's server root at the *repo* root, while React Native's Gradle
 *     plugin passes `--entry-file` relative to the *app* directory. The two
 *     disagree by exactly the depth of `apps/mobile`, so the release bundle
 *     step dies with "Unable to resolve module ./../../node_modules/
 *     expo-router/entry.js" — a path that looks correct and is off by two
 *     levels. Setting this pins the server root to the app directory, which is
 *     what the Gradle-supplied path is relative to. Debug builds never hit it
 *     because they skip bundling entirely.
 *
 *  2. **`ANDROID_HOME`.** `android/` is generated by `expo prebuild` and is
 *     gitignored, so `local.properties` does not survive a regeneration. The
 *     SDK is located here instead, and the failure names the fix rather than
 *     saying "SDK location not found".
 *
 * Usage: node scripts/build-android.mjs [debug|release]
 *
 *   debug    needs Metro running and reachable from the phone; no JS is
 *            embedded, so it is only useful alongside `npm start`.
 *   release  self-contained and installable on its own. Signed with the debug
 *            keystore, which is fine for testing and is NOT fine for anything
 *            you would put in front of a user.
 */
import { execFileSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { homedir, platform } from 'node:os'

const APP_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const ANDROID_DIR = join(APP_ROOT, 'android')

const variant = (process.argv[2] ?? 'release').toLowerCase()
if (variant !== 'debug' && variant !== 'release') {
  console.error(`Unknown variant "${variant}". Expected "debug" or "release".`)
  process.exit(1)
}

/** The usual install locations, in the order they are worth trying. */
function findAndroidSdk() {
  const fromEnv = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT
  if (fromEnv && existsSync(fromEnv)) return fromEnv

  const candidates =
    platform() === 'darwin'
      ? [join(homedir(), 'Library', 'Android', 'sdk')]
      : platform() === 'win32'
        ? [join(homedir(), 'AppData', 'Local', 'Android', 'Sdk')]
        : [join(homedir(), 'Android', 'Sdk'), '/usr/lib/android-sdk']

  return candidates.find((path) => existsSync(path)) ?? null
}

const sdk = findAndroidSdk()
if (!sdk) {
  console.error(
    'Could not find the Android SDK.\n' +
      'Install it with Android Studio, or set ANDROID_HOME to point at it.',
  )
  process.exit(1)
}

if (!existsSync(ANDROID_DIR)) {
  console.error(
    'No android/ directory. It is generated, not committed — run:\n' +
      '  npx expo prebuild --platform android',
  )
  process.exit(1)
}

const task = variant === 'release' ? 'assembleRelease' : 'assembleDebug'
const gradlew = platform() === 'win32' ? 'gradlew.bat' : './gradlew'

console.log(`Building ${variant} with SDK at ${sdk}`)

try {
  execFileSync(gradlew, [task, '--console=plain'], {
    cwd: ANDROID_DIR,
    stdio: 'inherit',
    env: {
      ...process.env,
      ANDROID_HOME: sdk,
      ANDROID_SDK_ROOT: sdk,
      // See the note at the top — without this the release bundle step fails.
      EXPO_NO_METRO_WORKSPACE_ROOT: '1',
    },
  })
} catch {
  // Gradle has already printed the reason; a stack trace from here would only
  // bury it.
  process.exit(1)
}

const apk = join(ANDROID_DIR, 'app', 'build', 'outputs', 'apk', variant, `app-${variant}.apk`)
console.log(`\n${existsSync(apk) ? apk : `Built, but no APK at ${apk}`}`)
